chords/urls.py
from django.conf.urls import url

from . import views


song_path = r'^song/(?P<song_slug>[\w\-]+)'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(song_path + '/$', views.song, name='song'),
    url(song_path + '/.json/$', views.song_json, name='song_json'),
    url(song_path + '/add_bookmark/$', views.add_bookmark, name='add_bookmark'),
    url(song_path + '/remove_bookmark/$', views.remove_bookmark, name='remove_bookmark'),
    url(r'^artist/(?P<artist_slug>[\w\-]+)/$', views.artist, name='artist'),
    url(r'^add_song/$', views.AddSongView.as_view(), name='add_song'),
    url(r'^verify_song/$', views.verify_song, name='verify_song'),
    url(r'^song_submitted/$', views.song_submitted, name='song_submitted'),
    url(r'^user/(?P<username>[\w]+)/$', views.user, name='user'),
    url(r'^popular/$', views.popular, name='popular'),
    url(r'^recently_added/$', views.recently_added, name='recently_added'),
    url(r'^search/$', views.search, name='search'),
    url(r'^bookmarks/$', views.bookmarks, name='bookmarks'),
    url(r'^add_comment/$', views.AddCommentView.as_view(), name='add_comment'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^contact_done/$', views.contact_done, name='contact_done'),
]

guitarchords/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from django.core.urlresolvers import reverse_lazy
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.generic import TemplateView

from registration.backends.default.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail
from password_validation import validate_password

from chords.sitemaps import StaticViewSitemap, ArtistSitemap, SongSitemap, UserSitemap


class RegistrationViewUniqueEmailPasswordValidation(RegistrationView):
    class ValidatingRegistrationFormUniqueEmail(RegistrationFormUniqueEmail):
        def clean_password1(self):
            password1 = self.cleaned_data.get('password1')
            validate_password(password1)
            return password1

    form_class = ValidatingRegistrationFormUniqueEmail


def login_user(request):
    if request.method == 'POST' and not 'remember_me' in request.POST:
        request.session.set_expiry(0)
    return auth.views.login(request, 'registration/login.html')


sitemaps = {
    'static' : StaticViewSitemap,
    'songs' : SongSitemap,
    'artists' : ArtistSitemap,
    'users' : UserSitemap,
}


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('chords.urls', namespace='chords')),
    url(r'^accounts/login/$', login_user, name='auth_login'),
    url(r'^accounts/register/$', RegistrationViewUniqueEmailPasswordValidation.as_view(), name='registration_register'),
    url(r'^accounts/password/change/$', 'password_validation.views.password_change',
        {'post_change_redirect': reverse_lazy('auth_password_change_done')}, name='auth_password_change'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'password_validation.views.password_reset_confirm',
        {'post_reset_redirect': reverse_lazy('auth_password_reset_complete')}, name='auth_password_reset_confirm'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain')),
]

chords/forms.py
from django import forms
from django.core.mail import mail_managers

from .models import Song, Comment
from .utils import strip_whitespace_lines

from captcha.fields import ReCaptchaField


class AddSongForm(forms.ModelForm):
    artist_txt = forms.CharField(
            max_length=100,
            label='Artist',
            help_text='In Surname Name format.'
    )

    class Meta:
        model = Song
        fields = ['title', 'artist_txt', 'genre', 'video', 'content', 'tabs']

        widgets = {
            'content' : forms.Textarea(attrs={'cols': 70, 'rows': 35}),
        }
        labels = {
            'title' : 'Title',
            'genre' : 'Genre',
            'video' : 'Video (optional)',
            'tabs'  : 'This version contain tabs',
        }
        help_texts = {
            'genre' : 'Pick the closest, or Other.',
            'video' : 'Youtube, Vimeo, Dailymotion.',
        }
        error_messages = {
            'content' : {
                'required' : "Remember to include the song!"
            },
        }


    def clean(self):
        if 'content' in self.cleaned_data:
            self.cleaned_data['content'] = strip_whitespace_lines(
                    self.cleaned_data['content'])
        return self.cleaned_data


class AddCommentForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Comment
        exclude = ['pub_date']

        widgets = {
            'user' : forms.HiddenInput(),
            'song' : forms.HiddenInput(),
            'content' : forms.Textarea(attrs={'rows': 8}),
        }
        labels = {
            'content' : 'Leave a comment',
        }


class SearchForm(forms.Form):
    SEARCH_ARTIST = 'AR'
    SEARCH_SONG = 'SO'
    SEARCH_USER = 'US'

    SEARCHBY_CHOICES = (
        (SEARCH_ARTIST, 'Artist'),
        (SEARCH_SONG, 'Song'),
        (SEARCH_USER, 'User'),
    )

    GENRE_ALL = 'ALL'
    GENRE_CHOICES = ((GENRE_ALL, 'All'),) + Song.GENRE_CHOICES

    INCLUDE_TABS = 'IT'
    CHORDS_ONLY = 'CO'

    TABS_CHOICES = (
            (INCLUDE_TABS, 'Include Tabs'),
            (CHORDS_ONLY, 'Chords only'),
    )

    searchBy = forms.ChoiceField(label='Search by', choices=SEARCHBY_CHOICES)
    keywords = forms.CharField(label='Keywords', max_length=100, required=False)
    genre = forms.ChoiceField(label='Genre', choices=GENRE_CHOICES, required=False)
    tabs = forms.ChoiceField(label='Tabs', choices=TABS_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['keywords'].widget.attrs['placeholder'] = 'Search for...'

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    subject = forms.CharField(label='Subject', max_length=100)
    body = forms.CharField(label='Your message', widget=forms.Textarea())

    def send_emails(self):
        msg = 'Mail from: {0}\n\n'.format(self.cleaned_data['email'])
        msg += self.cleaned_data['body']

        mail_managers(
                subject=self.cleaned_data['subject'],
                message=msg,
                fail_silently=False
        )

chords/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.views.generic.edit import FormView
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q

import os

from .models import Artist, Song, Comment, User, MyCache
from .forms import AddSongForm, AddCommentForm, ContactForm, SearchForm
from .utils import slugify_greek


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


def index(request):
    if 'song_data' in request.session:
        del request.session['song_data']
    context = {
        'recent_songs' : MyCache.recent_songs()[:7],
        'popular_songs' : MyCache.popular_songs()[:7],
        'song_count' : MyCache.published_songs_count(),
        'artist_count' : MyCache.artists_count(),
        'user_count' : User.objects.count(),
    }
    return render(request, 'chords/index.html', context)

def song(request, song_slug):
    context = {}
    if request.user.is_authenticated():
        song = get_object_or_404(Song, Q(slug=song_slug),
            Q(published=True) | Q(sender=request.user))
        song.viewedBy.add(request.user)

        context['bookmarked'] = bool(request.user.bookmarks.filter(slug=song.slug))
    else:
        song = get_object_or_404(Song, slug=song_slug, published=True)

    comments = song.comments.all().order_by('pub_date')
    comment_form = AddCommentForm(initial={
        'user' : request.user.id,
        'song' : song.id})
    context.update({'song' : song, 'preview' : False,
                    'comments' : comments, 'comment_form' : comment_form})
    return render(request, 'chords/song.html', context)

def song_json(request, song_slug):
    song = get_object_or_404(Song, slug=song_slug, published=True)
    return JsonResponse(song.tojson())

def artist(request, artist_slug):
    artist = get_object_or_404(Artist, slug=artist_slug)
    songs = artist.songs.filter(published=True).order_by('title')
    context = {'artist' : artist, 'songs' : songs}
    return render(request, 'chords/artist.html', context)

def user(request, username):
    user = get_object_or_404(User, username=username)
    if request.user.is_authenticated() and request.user == user:
        songs = user.songs.all()
    else:
        songs = user.songs.filter(published=True)

    songs = songs.order_by('artist__name', 'title')
    context = {'theuser' : user, 'songs' : songs}
    return render(request, 'chords/user.html', context)

def popular(request):
    songs = MyCache.popular_songs()[:100]
    return render(request, 'chords/popular.html', {'songs' : songs})

def recently_added(request):
    songs = MyCache.recent_songs()[:100]
    return render(request, 'chords/recently_added.html', {'songs' : songs})

def search(request):
    searchBy = request.GET.get('searchBy', SearchForm.SEARCH_SONG)
    keywords = request.GET.get('keywords', '')
    genre = request.GET.get('genre', SearchForm.GENRE_ALL)
    tabs = request.GET.get('tabs', SearchForm.INCLUDE_TABS)
    orderBy = request.GET.get('orderBy', '')

    form = SearchForm(initial={'searchBy' : searchBy, 'keywords' : keywords,
                               'genre' : genre, 'tabs' : tabs})
    context = {'form' : form}

    if keywords:
        keyword_slug = slugify_greek(keywords)

        if searchBy == SearchForm.SEARCH_ARTIST:
            context['searchBy'] = 'artist'
            results = Artist.objects.filter(slug__contains=keyword_slug)
        elif searchBy == SearchForm.SEARCH_SONG:
            context['searchBy'] = 'song'
            results = Song.objects.filter(
                    slug__contains=keyword_slug, published=True)

            if genre != SearchForm.GENRE_ALL:
                results = results.filter(genre=genre)
            if tabs == SearchForm.CHORDS_ONLY:
                results = results.filter(tabs=False)
        else:
            context['searchBy'] = 'user'
            results = User.objects.filter(username__icontains=keywords)

        order_dict = {
                SearchForm.SEARCH_ARTIST :
                    {'nameAsc' : 'name', 'nameDesc' : '-name'},
                SearchForm.SEARCH_SONG :
                    {'nameAsc' : 'title', 'nameDesc' : '-title',
                     'artistAsc' : 'artist__name', 'artistDesc' : '-artist__name',
                     'genreAsc' : 'genre', 'genreDesc' : '-genre',
                     'tabsAsc' : '-tabs', 'tabsDesc' : 'tabs'},
                SearchForm.SEARCH_USER :
                    {'nameAsc' : 'username', 'nameDesc' : '-username'},
        }

        if orderBy:
            context['results'] = results.order_by(order_dict[searchBy][orderBy])
            html = render_to_string('chords/search_results_body.html', context)
            return HttpResponse(html)

        results = results.order_by(order_dict[searchBy]['nameAsc'])
        context.update({'results' : results, 'query' : keywords})

    return render(request, 'chords/search.html', context)

class ContactView(FormView):
    form_class = ContactForm
    template_name = 'chords/contact.html'
    success_url = reverse_lazy('chords:contact_done')

    def get_initial(self):
        if self.request.user.is_authenticated():
            return {'email' : self.request.user.email}
        return {}

    def form_valid(self, form):
        form.send_emails()
        return super(ContactView, self).form_valid(form)

def contact_done(request):
    return render(request, 'chords/contact_done.html', {})

class AddCommentView(LoginRequiredMixin, FormView):
    form_class = AddCommentForm
    template_name = 'chords/display_comment.html'

    def post(self, request, *args, **kwargs):
        if request.POST.get('testing', '') == 'True':
            os.environ['RECAPTCHA_TESTING'] = 'True'
            request.POST._mutable = True
            request.POST['g-recaptcha-response'] = 'PASSED'
            request.POST._mutable = False

        form = self.form_class(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            comment = Comment(user=data['user'], song=data['song'],
                              content=data['content'])
            comment.save()

            os.environ['RECAPTCHA_TESTING'] = 'False'
            return HttpResponse(render_to_string(self.template_name,
                                                 {'comment' : comment}))

        return HttpResponse(status=400) # Bad Request

@login_required
def add_bookmark(request, song_slug):
    song = get_object_or_404(Song, Q(slug=song_slug),
        Q(published=True) | Q(sender=request.user))
    request.user.bookmarks.add(song)
    return HttpResponse()

@login_required
def remove_bookmark(request, song_slug):
    song = get_object_or_404(Song, slug=song_slug)
    request.user.bookmarks.remove(song)
    return HttpResponse()

@login_required
def bookmarks(request):
    songs = request.user.bookmarks.filter(
            Q(published=True) | Q(sender=request.user)
            ).order_by('artist__name', 'title')
    return render(request, 'chords/bookmarks.html', {'songs' : songs})

class AddSongView(LoginRequiredMixin, FormView):
    form_class = AddSongForm
    template_name = 'chords/add_song.html'
    success_url = reverse_lazy('chords:verify_song')

    def get_initial(self):
        return self.request.session.get('song_data', None)

    def form_valid(self, form):
        self.request.session['song_data'] = form.cleaned_data
        self.request.session['song_data']['user_txt'] = self.request.user.get_username()
        return super(AddSongView, self).form_valid(form)

@login_required
def verify_song(request):
    song_data = request.session.get('song_data', None)
    if song_data is None:
        return redirect('chords:add_song')

    song = Song(
        title=song_data['title'], artist=None, video=song_data['video'],
        genre=song_data['genre'], tabs=song_data['tabs'],
        content=song_data['content'])
    if song.video:
        song.video = song.get_embed_video_url()

    context = {'song' : song, 'artist_txt' : song_data['artist_txt'],
               'user_txt' : song_data['user_txt'], 'preview' : True}
    return render(request, 'chords/verify_song.html', context)

@login_required
def song_submitted(request):
    song_data = request.session.get('song_data', None)
    if song_data is None:
        return redirect('chords:add_song')

    try:
        artist = Artist.objects.get(slug=slugify_greek(song_data['artist_txt']))
    except Artist.DoesNotExist:
        artist = Artist(name=song_data['artist_txt'])
        artist.save()

    song = Song(
        title=song_data['title'], artist=artist, sender=request.user,
        video=song_data['video'], genre=song_data['genre'],
        tabs=song_data['tabs'], content=song_data['content'])
    song.save()

    del request.session['song_data']
    return render(request, 'chords/song_submitted.html', {})

chords/templates/chords/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <link rel="icon" href="{% static 'chords/img/favicon.ico' %}">
        <title>{% block title %}{% endblock %} - Chords</title>

        <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
        {% compress css %}
            <link rel="stylesheet" type="text/css" href="{% static 'chords/css/style.css' %}" />
        {% endcompress %}
    </head>

    <body>

    <nav class="navbar navbar-default">
        <div class="container">

            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'chords:index' %}">Guitar Chords</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="nav_recentlyadded"><a href="{% url 'chords:recently_added' %}">Recently added</a></li>
                    <li id="nav_popular"><a href="{% url 'chords:popular' %}">Popular</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'chords:add_song' %}">Send a song!</a></li>
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username}} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'chords:bookmarks' %}">My bookmarks</a></li>
                                <li><a href="{% url 'chords:user' user.username %}">My songs</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                                <li><a href="{% url 'auth_logout' %}?next=/">Logout</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Sign up</a></li>
                        <li><a href="{% url 'auth_login' %}">Log in</a></li>
                    {% endif %}
                </ul>

                <form class="navbar-form navbar-right" action="{% url 'chords:search' %}" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" name="keywords" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">Go</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}{% endblock %}
    </div>

    <div class="container footer">
        <hr />
        <footer class="text-center text-muted">
            <p>
            Copyright © 2015 Ilias Stamatis. All rights reserved. <br />
            <a href="{% url 'chords:contact' %}">Contact</a>
            · <a href="https://github.com/Ilias95/guitarchords">GitHub</a>
            · <a href="https://github.com/Ilias95/guitarchords/blob/master/LICENSE">License</a>
            <p>
        </footer>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="//s3.amazonaws.com/cc.silktide.com/cookieconsent.latest.min.js"></script>

    {% compress js %}
        {% block scripts_block %}{% endblock %}
    {% endcompress %}

    {% compress js %}
        <script type="text/javascript">
            window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website.",
                                            "dismiss":"Got it!",
                                            "learnMore":"More info",
                                            "link":"",
                                            "theme":"light-bottom"};
        </script>
    {% endcompress %}
    </body>
</html>

chords/templates/chords/contact.html
{% extends 'chords/base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block title %}Contact{% endblock %}

{% block body_block %}

<form id="contact_form" method="post" action="{% url 'chords:contact' %}">
    {% csrf_token %}
    <h3>Contact</h3>
    <hr />

    {{ form|bootstrap }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

{% block scripts_block %}
    <script src="{% static "chords/js/forms_validation.js" %}"></script>
{% endblock %}

chords/templates/chords/display_comment.html
<div class="comment">
    <p><a href="{% url 'chords:user' comment.user.get_username %}">{{ comment.user.get_username }}</a> • {{ comment.pub_date }}</p>
    <div class="comment_content">{{ comment.content }}</div>
    <br />
</div>

chords/templates/chords/index.html
{% extends 'chords/base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block body_block %}

<div class="row">
    <div class="col-md-12 text-center">
        <h1>Welcome to Guitar Chords!</h1>
        <p class="h3">Find <span class="colored_blue">chords</span> and <span class="colored_blue">tabs</span> for your favorite songs here</p>
        <br />
        <img class="img-responsive center-block" src="{% static 'chords/img/guitar_index.jpg'%}" alt="Guitar image" width="350">
        <br />
        <p class="h4">
            We keep a collection of {{ song_count }} <a href="{% url 'chords:search' %}?searchBy=SO">songs</a>
            and {{ artist_count }} <a href="{% url 'chords:search' %}?searchBy=AR">artists</a> from {{ user_count }}
            <a href="{% url 'chords:search' %}?searchBy=US">users</a> and still counting...
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-6 text-center">
        <h2>Recently added songs</h2>
        {% if recent_songs %}
            <ul>
                {% for song in recent_songs %}
                    <li><a href="{% url 'chords:song' song.slug %}">{{ song.full_title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p><strong>No songs present at the moment</strong></p>
        {% endif %}
    </div>
    <div class="col-md-6 text-center">
        <h2>Most popular songs</h2>
        {% if popular_songs %}
            <ul>
                {% for song in popular_songs %}
                    <li><a href="{% url 'chords:song' song.slug %}">{{ song.full_title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p><strong>No songs present at the moment</strong></p>
        {% endif %}
    </div>
</div>

{% endblock %}

chords/templates/chords/panel_form_snippet.html
<div class="panel panel-primary center-block" id="{{ panel_id }}">
    <div class="panel-heading">
        <h3 class="panel-title text-center"><strong>{{ title }}</strong></h3>
    </div>
    <div class="panel-body">

chords/templates/chords/popular.html
{% extends 'chords/base.html' %}

{% block title %}Popular content{% endblock %}

{% block body_block %}

<div class="row">
    <div class="center-block text-center table-container" id="popular_container">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th class="text-center h2">Most Popular Songs</th>
                </tr>
            </thead>

            <tbody>
                {% for song in songs %}
                    <tr class="list-group">
                        <td>{{ forloop.counter }}.</td>
                        <td><a href="{% url 'chords:song' song.slug %}">{{ song.title }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if not songs %}
            <p><strong>No songs present at the moment</strong></p>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block scripts_block %}
    <script> $(function() { $('#nav_popular').addClass('active'); }); </script>
{% endblock %}

chords/templates/chords/recently_added.html
{% extends 'chords/base.html' %}

{% block title %}Recently added{% endblock %}

{% block body_block %}

<div class="row">
    <div class="center-block text-center table-container" id="recentlyadded_container">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th class="text-center h2">Recently added songs</th>
                </tr>
            </thead>

            <tbody>
                {% for song in songs %}
                    <tr class="list-group">
                        <td>{{ song.pub_date|date:"SHORT_DATE_FORMAT" }}</td>
                        <td><a href="{% url 'chords:song' song.slug %}">{{ song.title }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if not songs %}
            <p><strong>No songs present at the moment</strong></p>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block scripts_block %}
    <script> $(function() { $('#nav_recentlyadded').addClass('active'); }); </script>
{% endblock %}

chords/templates/chords/search.html
{% extends 'chords/base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Search{% endblock %}

{% block body_block %}

{% if not query %}
    <h3>Search for songs, users and artists</h3>
    <br />
{% endif %}

<form id="search_form" class="form-inline" action="{% url 'chords:search' %}" method="get">
    {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.auto_id }}">{{ field.label }}</label>
            {{ field }}
        </div>
    {% endfor %}
    <div class="form-group">
        <label id="submit_label">Go</label>
        <button type="submit" class="btn btn-primary">{% trans 'Search' %}</button>
    </div>
</form>
<input type="hidden" id="id_orderBy" value="nameAsc" />
<br />

{% if results %}
    <table class="table" id="search_table">
        <thead>
            <tr>
                <th><a href="javascript:;">Name</a></th>
                {% if searchBy == 'song' %}
                    <th><a href="javascript:;">Artist</a></th>
                    <th><a href="javascript:;">Genre</a></th>
                    <th><a href="javascript:;">Tabs</a></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% include "chords/search_results_body.html" %}
        </tbody>
    </table>
    <p><strong>We found {{ results.count }} relative result{{ results.count|pluralize }}.</strong></p>
{% elif query %}
    <p><strong>No results matched your search criteria.</strong></p>
{% endif %}

{% endblock %}

{% block scripts_block %}
    <script src="{% static "chords/js/search_order_ajax.js" %}"></script>
{% endblock %}

chords/templates/chords/search_results_body.html
{% for result in results %}
    <tr>
        {% if searchBy == 'song' %}
            <td><a href="{% url 'chords:song' result.slug %}">{{ result }}</a></td>
            {% if result.artist %}
                <td><a href="{% url 'chords:artist' result.artist.slug %}">{{ result.artist.name }}</a></td>
            {% else %}
                <td>-</td>
            {% endif %}
            <td>{{ result.genre_str }}</td>
            <td>{% if result.tabs %}Yes{% else %}No{% endif %}</td>
        {% elif searchBy == 'artist' %}
            <td><a href="{% url 'chords:artist' result.slug %}">{{ result }}</a></td>
        {% else %}
            <td><a href="{% url 'chords:user' result.get_username %}">{{ result }}</a></td>
        {% endif %}
    </tr>
{% endfor %}

chords/templates/chords/user.html
{% extends 'chords/base.html' %}
{% load staticfiles %}

{% block title %}{{ theuser.username }}{% endblock %}

{% block body_block %}

<div class="row header text-center">
    <h3>Songs sent by {{ theuser.username }}</h3>
</div>

<div class="row" id="present_songs">
    {% if songs %}
        {% for song in songs %}
            <li><a href="{% url 'chords:song' song.slug %}">{{ song.full_title }}</a></li>
        {% endfor %}

        <div id="col1" class="col-md-4"> <ul> </ul> </div>
        <div id="col2" class="col-md-4"> <ul> </ul> </div>
        <div id="col3" class="col-md-4"> <ul> </ul> </div>
    {% else %}
        <p class="text-center">This user hasn't sent any songs yet.</p>
    {% endif %}
</div>

{% endblock %}

{% block scripts_block %}
    <script src="{% static "chords/js/present.js" %}"></script>
{% endblock %}

chords/templates/chords/user_bookmarks.html
{% extends 'chords/base.html' %}
{% block title %}Your bookmarks{% endblock %}

{% block body_block %}

{% if songs %}
    <ul>
    {% for song in songs %}
    <li><a href="{% url 'chords:song' song.slug %}">{{ song.full_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <strong>Your bookmarks are empty.</strong>
{% endif %}

{% endblock %}